CREATE DATABASE vendas_sucos;
USE vendas_sucos;
CREATE TABLE PRODUTOS(
CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);


CREATE TABLE VENDEDORES(
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADMISSAO  DATE NULL,
FERIAS BIT(1) NULL,
PRIMARY KEY (MATRICULA)
);


CREATE TABLE VENDAS(
NUMERO VARCHAR(5) NOT NULL,
DATA DATE,
CPF VARCHAR(11),
MATRICULA VARCHAR(5),
IMPOSTO FLOAT,
PRIMARY KEY (NUMERO) ,
FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF),
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA)
);

CREATE TABLE ITENS_NOTAS (
NUMERO VARCHAR(5),
CODIGO VARCHAR (10),
QUANTIDADE INT,
PRECO FLOAT,
PRIMARY KEY (NUMERO,CODIGO),
FOREIGN KEY (NUMERO) REFERENCES VENDAS(NUMERO),
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS(CODIGO)
);


 RENAME TABLE VENDEDORES TO TABELA_DE_VENDEDORES;

ALTER TABLE tabela_de_vendas RENAME NOTAS;

