
# CONSULTAS AVANÇADAS

 
SELECT EMBALAGEM , TAMANHO FROM tabela_de_produtos;
## COMANDO DISCTINCT QUE NÃO EXIBE NO RETORNO VALORES QUE SE REPETEM
SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos
WHERE SABOR = 'LARANJA';


### SUPONHAMOS QUE NOS PERGUNTASSEM QUAIS SÃO AS EMBALAGENS E TAMANHOS DISPONIVEIS PARA O SUCO DO TAMANHO LARANJA...

#### RODARIAMOS ESSE COMANDO QUE NOS RETORNARIA DA FORMA MAIS PERFORMATICA OS DADOS REQUISITADOS
SELECT DISTINCT EMBALAGEM, TAMANHO,SABOR FROM tabela_de_produtos 
WHERE SABOR = 'LARANJA';

### Quais são os bairros da cidade do Rio de Janeiro que possuem clientes?
SELECT DISTINCT BAIRRO, NOME, CIDADE FROM tabela_de_clientes 
WHERE CIDADE = 'RIO DE JANEIRO'; 


## comando limit para limitar a consulta

SELECT * FROM tabela_de_clientes LIMIT 4;


### LIMITANDO PELO MEIO DA TABELA

SELECT * FROM tabela_de_clientes LIMIT 4,7;

SELECT * FROM tabela_de_produtos;

SELECT * FROM tabela_de_produtos LIMIT 5;


SELECT * FROM tabela_de_produtos LIMIT 2,3;


SELECT * FROM tabela_de_produtos LIMIT 0,3;


SELECT * FROM notas_fiscais 
WHERE DATA_VENDA = '2017/01/01'
LIMIT 10;



### ORDENANDO DADOS DA TABELA 

SELECT * FROM tabela_de_clientes ORDER BY NOME;

SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA;

SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM tabela_de_produtos ORDER BY NOME_DO_PRODUTO;

SELECT * FROM tabela_de_produtos ORDER BY NOME_DO_PRODUTO DESC;
#### ORDENAÇÕES COMPOSTAS
SELECT * FROM tabela_de_produtos ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO ASC;


#### Qual (ou quais) foi (foram) a(s) maior(es) venda(s) 
#### do produto “Linha Refrescante - 1 Litro - Morango/Limão”, em quantidade? .

SELECT * FROM tabela_de_produtos 
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limão'
ORDER BY NOME_DO_PRODUTO DESC ;

SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;


## AGRUPANDO RESULTADOS
SELECT * FROM tabela_de_clientes;

SELECT ESTADO, LIMITE_DE_CREDITO FROM tabela_de_clientes;


SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabela_de_clientes group by ESTADO;


SELECT EMBALAGEM, PRECO_DE_LISTA FROM tabela_de_produtos;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM tabela_de_produtos GROUP BY EMBALAGEM;


SELECT EMBALAGEM ,COUNT(*) AS CONTADOR FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT BAIRRO ,SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes 
WHERE CIDADE = 'RIO DE JANEIRO'
GROUP BY BAIRRO;


SELECT ESTADO, BAIRRO ,SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes
WHERE CIDADE = 'RIO DE JANEIRO'
GROUP BY ESTADO,BAIRRO
ORDER BY BAIRRO;


#### Aproveitando o exercício do vídeo anterior quantos itens de venda existem para o produto '1101035' ?

SELECT MAX(QUANTIDADE) AS 'MAIOR QUANTIDADE' FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE;

SELECT  COUNT(*) AS CONTADOR FROM itens_notas_fiscais 
WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;



## COMANDO HAVING 

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes 
GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) > 810000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS 'MAIOR PRECO', MIN(PRECO_DE_LISTA) AS 'MENOR PRECO' FROM tabela_de_produtos
GROUP BY EMBALAGEM;


SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS 'MAIOR PRECO', MIN(PRECO_DE_LISTA) AS 'MENOR PRECO' FROM tabela_de_produtos
GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS 'MAIOR PRECO', MIN(PRECO_DE_LISTA) AS 'MENOR PRECO' FROM tabela_de_produtos
GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80 AND MAX(PRECO_DE_LISTA) >=5;

SELECT CPF, COUNT(*) AS SOMA FROM notas_fiscais 
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF 
HAVING COUNT(*) >= 2000;


## COMANDO CASE

SELECT * FROM tabela_de_produtos;

### SEMELHANTE AO CASE EM LINGUAGENS DE PROGRAMACAO 

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO' 
	WHEN PRECO_DE_LISTA >= 7 and PRECO_DE_LISTA < 12 then 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
	END AS STATUS_PRODUTO
 FROM tabela_de_produtos;
 
 
 SELECT EMBALAGEM, 
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO' 
	WHEN PRECO_DE_LISTA >= 7 and PRECO_DE_LISTA < 12 then 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
	END AS STATUS_PRODUTO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
 FROM tabela_de_produtos
 WHERE SABOR = 'MANGA'
 GROUP BY EMBALAGEM,
	CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO' 
	WHEN PRECO_DE_LISTA >= 7 and PRECO_DE_LISTA < 12 then 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END
ORDER BY EMBALAGEM;
 
SELECT * FROM tabela_de_clientes;
 
 SELECT NOME,
CASE 
	WHEN YEAR(DATA_DE_NASCIMENTO) <=1990 THEN 'VELHO'
    WHEN YEAR(DATA_DE_NASCIMENTO) BETWEEN 1990 AND 1995 THEN 'JOVENS'
    ELSE 'CRIANÇAS' 
    END AS CLASSIFICACAO_DE_IDADE FROM tabela_de_clientes;

