# FUNÇOES MYSQL

## FUNÇOES DE STRING

SELECT LTRIM('       OLÁ') AS LTRIM;

SELECT RTRIM('OLÁ     ') AS RTRIM;

SELECT TRIM('       OLÁ        ') AS TRIM;


SELECT CONCAT("OLA","  ","MUNDO") AS CONCAT;


SELECT UPPER('ola mundo')as UPPER ;


SELECT SUBSTRING('OLA, TUDO BEM?',6,4) AS SUBSTRING;

SELECT CONCAT(NOME,'(',CPF,')') AS RESULTADO FROM tabela_de_clientes;


SELECT CONCAT(NOME,'(',CPF,')', '(',ENDERECO_1,')','(',ENDERECO_2,')','(',ESTADO,')','(',CIDADE,')') AS RESULTADO FROM tabela_de_clientes;

## FUNÇOES DE DATA 

SELECT ADDDATE("2017-06-15",INTERVAL 1 YEAR);

SELECT ADDTIME("2017-06-15 12:08", "2");

SELECT CURDATE();

SELECT CURRENT_TIME();


SELECT CURRENT_TIMESTAMP();


SELECT YEAR(CURRENT_TIMESTAMP());

SELECT DAY(CURRENT_TIMESTAMP());

SELECT MONTH(CURRENT_TIMESTAMP());


SELECT DATEDIFF(CURRENT_TIMESTAMP(),'2002-04-28');

SELECT DATE_SUB(CURRENT_TIMESTAMP(),INTERVAL 5 DAY) AS RESULTADO;


SELECT CURRENT_TIMESTAMP() AS HOJE 
,DATE_SUB(CURRENT_TIMESTAMP(),INTERVAL 5 DAY) AS RESULTADO;


SELECT DISTINCT DATA_VENDA,
 DAYNAME(DATA_VENDA) AS `NOME DIA`,
 MONTHNAME(DATA_VENDA) AS `NOME MES`,
 YEAR(DATA_VENDA) AS `ANO` FROM NOTAS_FISCAIS;


SELECT IDADE FROM tabela_de_clientes;
### SUBDATE USAR TAMESTAMPDIFF PARA SUBRATAÇÃO DE ANOS POIS SUBDATE RETORNA MAIOR MARGEM DE ERRO
SELECT YEAR(SUBDATE(curdate(), INTERVAL YEAR(DATA_DE_NASCIMENTO) YEAR)) AS RODA_REESCRITA, NOME FROM
tabela_de_clientes;

SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS   IDADE
FROM  tabela_de_clientes;

### FUNÇÕES MATEMATICAS
SELECT ABS(-243.5);


SELECT SQRT(64);


SELECT (23+((25-2)/2)*45) AS RESULT;


SELECT CEILING(12.43643536535456345) AS RESULT;


SELECT ROUND(12.2);

SELECT FLOOR(12.99999);


SELECT RAND() AS ALEATORIO;

SELECT NUMERO, QUANTIDADE, PRECO , QUANTIDADE*PRECO AS FATURAMENTO FROM itens_notas_fiscais;

SELECT NUMERO, QUANTIDADE, PRECO , ROUND(QUANTIDADE*PRECO ,2) AS FATURAMENTO FROM itens_notas_fiscais;

SELECT FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO)))  AS IMPOSTO 
FROM itens_notas_fiscais as ITENS inner join notas_fiscais as NOTAS 
ON ITENS.NUMERO = NOTAS.NUMERO WHERE YEAR(DATA_VENDA) = 2016
GROUP BY(DATA_VENDA);

### MANIPULAÇÕES DE TIPO 

SELECT current_timestamp() AS RESULTADO;

SELECT CONCAT("O DIA DE HOJE É : ",CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT("O DIA DE HOJE É : ",CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT("O DIA DE HOJE É : ",DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%y - %U')) AS RESULTADO;

### TRANSFORMANDO EM STRING
SELECT CONVERT(23.3, CHAR) AS RESULTADO;


SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO;

SELECT CONCAT("O CLIENTE: ",NOME,"FATUROU ", ROUND(CONSULT.QUANTIDADE) * CONSULT.PRECO, "NO ANO DE ", YEAR(CONSULT.DATA_VENDA)) AS RESULTADO FROM tabela_de_clientes INNER JOIN 
(SELECT I.QUANTIDADE, I.PRECO, N.DATA_VENDA AS DATAVENDA, N.CPF AS CPF FROM itens_notas_fiscais AS I INNER JOIN notas_fiscais AS N
ON I.NUMERO = N.NUMERO) CONSULT;




SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CAST(SUM(INF.QUANTIDADE * INF.preco) AS char (20))
 , ' no ano ', CAST(YEAR(NF.DATA_VENDA) AS char (20))) AS SENTENCA FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TC.NOME, YEAR(DATA_VENDA);